# Generated by Django 4.2.3 on 2023-08-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0004_project_filament_needed_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='print_queue_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hub.project')),
            ],
        ),
    ]
