# Generated by Django 4.2.3 on 2023-08-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0005_printinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintingList',
            new_name='Printing',
        ),
    ]
