# Generated by Django 4.2.3 on 2023-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0006_rename_printinglist_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
