# Generated by Django 4.2.3 on 2023-08-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0007_printing_number_alter_printing_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printing',
        ),
    ]
