# Generated by Django 4.2.3 on 2023-08-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0009_printing'),
    ]

    operations = [
    ]
