# Generated by Django 4.2.3 on 2023-08-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0010_auto_20230807_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printing',
        ),
    ]
