# Generated by Django 4.2.3 on 2023-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0016_alter_printingque_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingque',
            name='is_removed_from_queue',
            field=models.BooleanField(default=False),
        ),
    ]
