# Generated by Django 4.2.3 on 2023-08-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0017_printingque_is_removed_from_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='project_images/'),
        ),
    ]
